export default {
  app:{
    currentBanner:null,
    selectedGroup:null,
    selectedPath:null,
    selectedSegment:null,
    selectedDiv:null,
    animaticonGroups:[],
    paths:[],
    bones:[],
    divs:[],
    mainScene:null,
    showShapesModal:false,
    renderer:null,
    size:{
      width:500,
      height:500
    }
  },
  animation:{
    controls:[],
    clock:null,
    groupControls:[],
    selectedControl:null,
    isAnimationCompleted:false,
    showAnimationControlsSetModal:false,
    preDefinedAnimationControlSets:{}
  },
  api:{

  },
  global:{
    showGlobalMessage:false,
    globalMessage:'',
    showAnimaticonObjSetsModal:false
  },
  search:{
    objectsSearchResults:[],
    bannersSearchResults:[]
  }
};
